name: Compila e integra a dev3

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name : Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Levantar contenedor
        env:
          DOCKER_HOST: ${{ secrets.DEV3_DOCKER_HOST }}
          DOCKER_TLS_VERIFY: 1
          DOCKER_CERT_PATH: ${{ secrets.DOCKCERTS }}
        run: |
          docker info | grep -E 'Name:|Server Version'
          docker compose up -d --build --force-recreate
